### ISSUE TITLE
Discord reponse issue

### ISSUE THREAD

**Issue by thexbasic** [SinusBot/docker#10]
Hi there,

since you dont have an official project for the SinusBot and I'm using the docker-version I thought I'd open it here.
So I was already running a TS3 instance on the bot, and everything is going fine (with control via TS3 etc). Now I added a Discord one to try some things out. Set everything up, added the bot to a server etc.
It even reacts to commands written in any chat. BUT even though it reacts (performs e.g. !stop) it wont respond. E.g. when using !playing, nothing is written in that channel by the bot, but when PM'ing the bot, it will respond.
I've checked the permissions and the bot should be able to send messages.
Reconnecting and restarting didnt fix it.

Im glad to provide more info if needed :) Thanks in advance

**Comment by irgendwr** [comment]
Hi,

yup this is a known issue with the sinusbot. Discord support is still in it's early phase and many things are missing.
I'm closing this issue because it has not really anything to do with this repo but be already have created an issue in our internal tracker and it's going to be fixed in a future release (no ETA though).
Thanks for reporting it and showing interest in the bot 😃

**Comment by irgendwr** [comment]
This is now fixed in an internal test release, it will be available in the next version (0.14), no ETA.
